name: Automated Attendance Punching

on:
  #schedule:
    # 8:30 出勤打刻 (月曜日から金曜日のみ)
    # JSTベースで実行するため-9h。 actionsのスケジュールは結構遅れるため、8:30にしている
  #  - cron: "30 23 * * 0-4"
    # 18:00 退勤打刻 (月曜日から金曜日のみ)
  #  - cron: "30 9 * * 1-5"
  workflow_dispatch:

jobs:
  punch_in_out:
    runs-on: ubuntu-latest

    steps:
      - name: Punch In or Out
        env:
          TOKEN: ${{ secrets.AKASHI_TOKEN }}
        run: |
          # Define a list of holidays (in YYYY-MM-DD format)
          HOLIDAYS=(
            "2024-01-01" # 元日
            "2024-01-08" # 成人の日
            "2024-02-11" # 建国記念の日
            "2024-02-12" # 振替休日
            "2024-02-23" # 天皇誕生日
            "2024-03-20" # 春分の日
            "2024-04-29" # 昭和の日
            "2024-05-03" # 憲法記念日
            "2024-05-04" # みどりの日
            "2024-05-05" # こどもの日
            "2024-05-06" # 振替休日
            "2024-07-15" # 海の日
            "2024-08-11" # 山の日
            "2024-08-12" # 振替休日
            "2024-09-16" # 敬老の日
            "2024-09-22" # 秋分の日
            "2024-09-23" # 振替休日
            "2024-10-14" # スポーツの日
            "2024-11-03" # 文化の日
            "2024-11-04" # 振替休日
            "2024-11-23" # 勤労感謝の日
            "2025-01-01" # 元日
            "2025-01-13" # 成人の日
            "2025-02-11" # 建国記念の日
            "2025-02-23" # 天皇誕生日
            "2025-02-24" # 振替休日
            "2025-03-20" # 春分の日
            "2025-04-29" # 昭和の日
            "2025-05-03" # 憲法記念日
            "2025-05-04" # みどりの日
            "2025-05-05" # こどもの日
            "2025-05-06" # 振替休日
            "2025-07-21" # 海の日
            "2025-08-11" # 山の日
            "2025-09-15" # 敬老の日
            "2025-09-23" # 秋分の日
            "2025-10-13" # スポーツの日
            "2025-11-03" # 文化の日
            "2025-11-23" # 勤労感謝の日
            "2025-11-24" # 振替休日
          )

          # Add year-end holidays (December 28 to January 3)
          YEAR_END_HOLIDAYS=(
            "2024-12-28" "2024-12-29" "2024-12-30" "2024-12-31"
            "2025-01-01" "2025-01-02" "2025-01-03"
            "2025-12-28" "2025-12-29" "2025-12-30" "2025-12-31"
            "2026-01-01" "2026-01-02" "2026-01-03"
          )

          HOLIDAYS+=( "${YEAR_END_HOLIDAYS[@]}" )

          # Get the current date in JST
          CURRENT_DATE=$(date -u "+%Y-%m-%d" -d "+9 hours")

          # Check if today is a holiday
          for HOLIDAY in "${HOLIDAYS[@]}"; do
            if [ "$CURRENT_DATE" = "$HOLIDAY" ]; then
              echo "Today is a holiday ($HOLIDAY). Skipping punch in/out."
              exit 0
            fi
          done

          # Get the current hour in JST to determine punch type
          CURRENT_HOUR=$(date -u "+%H" -d "+9 hours")
          if [ "$CURRENT_HOUR" -ge 8 ] && [ "$CURRENT_HOUR" -lt 9 ]; then
            TYPE=11 # 出勤
            STAMPED_AT="$(date -u "+%Y/%m/%d 09:00:00" -d "+9 hours")"
          elif [ "$CURRENT_HOUR" = "18" ]; then
            TYPE=12 # 退勤
            STAMPED_AT="$(date -u "+%Y/%m/%d 18:00:00" -d "+9 hours")"
          else
            echo "This action is neither for punching in nor out."
            exit 1
          fi

          # Execute the curl command for punching in or out
          curl -X POST 'https://atnd.ak4.jp/api/cooperation/yojokintai/stamps' \
            -H "Content-Type: application/json" \
            -d "{\"token\": \"${TOKEN}\", \"type\": $TYPE, \"stampedAt\": \"${STAMPED_AT}\", \"timezone\": \"+09:00\"}"
